# Generated by qa-agent — SCRUM-68 — 2026-08-31
# Target: https://www.michelinman.com/auto/dealer-locator
# Viewport under test: Mobile (360x600)
# Scenarios tagged @todo reference steps that do not exist yet; see
# qa-report.html § Automation gap analysis for the full list.

@generated @SCRUM-68
Feature: SCRUM-68 — Dealer locator mobile behaviour at 360x600

  Background:
    Given I am on the "dealer locator" page

  @generated @sanity
  Scenario: S1 — Dealer locator page loads with its core mobile elements
    Then the "dealer search input" should be visible
    And the "top cities list" should be visible
    And there should be no console errors

  @generated @todo @ac-1
  Scenario: S2 — Search input is fully visible with no horizontal page overflow
    Then the "dealer search input" should be visible
    # @todo no step: page-level horizontal-overflow assertion not available; belongs in steps/common.steps.js

  @generated @ac-1
  Scenario: S3 — Locate me becomes visible once the search input is focused
    When I click the "dealer search input"
    Then the "locate me button" should be visible

  @generated @todo @from-comment @bug-1
  Scenario: S4 — Locate me is keyboard-reachable (Tab, then Enter) once visible
    When I click the "dealer search input"
    And I press "Tab"
    # @todo no step: asserting which element received keyboard focus is not available; belongs in steps/dealer-locator.steps.js
    Then the "locate me button" should be visible

  @generated @todo @ac-2
  Scenario: S5 — Top-cities scroller is swipeable and its fade gradients never block a tap
    Then the "top cities list" should be visible
    # @todo no step: horizontal-scroll-gesture simulation and gradient hit-testing not available; belongs in steps/dealer-locator.steps.js

  @generated @ac-2
  Scenario: S6 — Selecting a top city reaches its dealer results page
    When I click the first top city
    Then the dealer results should be visible
    And the URL should contain "dealer-locator"

  @generated @todo @ac-3
  Scenario: S7 — Dealer results stack single-column with no truncation at mobile width
    When I click the first top city
    Then the dealer results should be visible
    And I should see more than 1 "dealer cards"
    And every dealer card should have a "address"
    # @todo no step: single-column layout / text-truncation assertion at a given viewport is not available; belongs in steps/dealer-locator.steps.js

  @generated @ac-4 @bug-2
  Scenario: S8 — Dealer search page should have more than 5 cities
    Then I should see more than 5 "top cities"

  @generated @regression
  Scenario: S9 — Back button after viewing results restores the search page
    Given I am on the "dealer results atlanta" page
    When I go back
    Then the "dealer search input" should be visible

  @generated @regression
  Scenario: S10 — A results URL opened directly restores state (URL persistence)
    Given I am on the "dealer results atlanta" page
    Then the URL should contain "atlanta"
    And I should see more than 1 "dealer cards"

  @generated @todo @analytics
  Scenario: S12 — Analytics fires on interaction (TC-AN1)
    When I click the first top city
    # @todo no step: dataLayer / analytics-request assertion not available; belongs in steps/common.steps.js
    Then the dealer results should be visible
