# Generated by qa-agent — SCRUM-68 — 2026-08-27
# Target: https://www.michelinman.com/auto/dealer-locator
# Viewport: Mobile (360x600)
# Scenarios tagged @todo reference steps or registry entries that do not exist
# yet; see qa-report.html § Automation gap for the list.

@generated @SCRUM-68
Feature: SCRUM-68 — Dealer locator renders and functions correctly at mobile viewport 360x600

  Background:
    Given I am on the "dealer locator" page

  @generated @sanity
  Scenario: S1 — Dealer locator page loads with its core elements at 360x600
    Then the "dealer search input" should be visible
    And the "top cities list" should be visible
    And the "map" should be visible
    And there should be no console errors

  @generated @feature
  Scenario: S2 — Search input is visible and tappable on load
    Then the "dealer search input" should be visible

  @generated @sanity @todo
  Scenario: S3 — No horizontal page overflow at 360x600
    # @todo no step: asserting document.body.scrollWidth <= window.innerWidth
    # for horizontal overflow is not covered; belongs in steps/common.steps.js
    Then there should be no console errors

  @generated @ac-1 @bug-3
  Scenario: S4 — Top-cities list exposes more than 5 cities
    Then I should see more than 5 "top cities"

  @generated @feature
  Scenario: S5 — Selecting Atlanta reaches the results page with readable dealer cards
    When I click the first top city
    Then the dealer results should be visible
    And I should see more than 1 "dealer cards"
    And every dealer card should have a "address"

  @generated @feature
  Scenario: S6 — Free-text city search reaches the correct results page
    When I search for the city "Chicago"
    And I select the first autocomplete suggestion
    And I press "Enter"
    Then the dealer results should be visible
    And the URL should contain "chicago"

  @generated @boundary
  Scenario: S7 — Invalid search input does not navigate or crash
    When I search for the city "zzxxqq99nonsense"
    And I press "Enter"
    Then the "dealer search input" should be visible
    And there should be no console errors

  @generated @ac-1 @bug-1 @todo
  Scenario: S8 — "Locate me" button is visible and tappable on initial load
    Then the "locate me button" should be visible
    # @todo no step: the existing check only asserts current DOM visibility,
    # not "before any prior interaction with the search input"; a dedicated
    # pre-interaction assertion belongs in steps/dealer-locator.steps.js to
    # actually catch BUG-1 on regression

  @generated @boundary @todo
  Scenario: S9 — Rapid interaction with the top-cities list does not error
    # @todo no step: rapid repeated interaction / stress-clicking a collection
    # is not covered; belongs in steps/common.steps.js
    Then there should be no console errors

  @generated @boundary
  Scenario: S10 — Back button restores the search page after selecting a city
    When I click the first top city
    And I go back
    Then the "dealer search input" should be visible

  @generated @boundary
  Scenario: S11 — Atlanta results state persists on a fresh URL load
    Given I am on the "dealer results atlanta" page
    Then the dealer results should be visible
    And the URL should contain "atlanta"

  @generated @from-comment @todo
  Scenario: S12 — Find Dealers is reachable from the mobile nav in under 3 taps
    When I click the "main navigation"
    # @todo no step: opening the mobile hamburger toggle specifically (as
    # opposed to a desktop mega-nav) is not covered; belongs in
    # steps/common.steps.js
    Then the "find dealers link" should be visible

  @generated @regression @todo
  Scenario: S13 — Dealer locator product-line switch (Auto to Motorcycle)
    When I click the "dealer locator productline switch"
    # @todo no step: "dealer locator productline switch" is not in
    # registry.elements (support/pages.js) — needs its own entry, distinct
    # from the home hero widget's "auto productline tab"
    Then the "map" should be visible

  @generated @regression @bug-2 @todo
  Scenario: S14 — Map widget control row is reachable
    When I click the "map control row"
    # @todo no step: "map control row" (fullscreen/zoom/rotate controls) is
    # not in registry.elements (support/pages.js); the step and element both
    # need adding to steps/dealer-locator.steps.js and support/pages.js to
    # automate BUG-2 as a regression check
    Then the "map" should be visible

  @generated @regression
  Scenario: S15 — Footer link group renders
    Then the "footer" should be visible

  @generated @regression
  Scenario: S16 — Breadcrumb is present
    Then the "breadcrumb" should be visible

  @generated @analytics @todo
  Scenario: S17 — TC-AN1 analytics events fire during interaction
    # @todo no step: asserting window.dataLayer growth / analytics network
    # requests is not covered; belongs in steps/common.steps.js
    Then there should be no console errors
